CREATE TABLE waf_alarm_table(
	id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	action_id tinyint(4) NOT NULL,
	rule_id int(11) NOT NULL,
	happentime datetime NOT NULL,
	hostname varchar(255) NOT NULL,
	sip varchar(40) NOT NULL,
	sport smallint(11) unsigned NOT NULL,
	dip varchar(40) NOT NULL,
	dport smallint(11) unsigned NOT NULL,
	unique_id  varchar(24) NOT NULL,
	msg_id int(11) NOT NULL,
	matchs varchar(255) NOT NULL,
	severity_id tinyint(4) NOT NULL,
	tag_id  smallint(11) NOT NULL,
	user_agent varchar(255)  NOT NULL,
	url text NOT NULL,
	post text NOT NULL,
	response_code  smallint(11) NOT NULL DEFAULT 0,
	request_header text NOT NULL,
	response_header text NOT NULL,
	response_body text NOT NULL,
	country varchar(3) NOT NULL,
	province varchar(3) NOT NULL,
	city varchar(50) NOT NULL
) ENGINE = MyISAM DEFAULT CHARSET = latin1;